import type { NextConfig } from 'next';

const nextConfig: NextConfig = {
  typescript: {
    ignoreBuildErrors: true,
  },
  images: {
  remotePatterns: [
    {
      protocol: "https",
      hostname: "cwoswinjuiwcylcsufav.supabase.co",
      pathname: "/storage/v1/object/public/**",
    },
  ],
  deviceSizes: [640, 750, 828, 1080, 1200],
  imageSizes: [16, 32, 48, 64, 96, 128, 256],
  formats: ["image/avif", "image/webp"],
},
  async redirects() {
    return [
      { source: '/&', destination: '/', permanent: true },
      { source: '/$', destination: '/', permanent: true },
      { source: '/blog/giyim-alisverisinde-kupon-kullanimi', destination: '/blog', permanent: false },
      { source: '/marka/samsonite', destination: '/marka', permanent: false },
      { source: '/kampanya/lumberjack-alisverisinize-250-tl-maxipuan', destination: '/', permanent: true },
      { source: '/kampanya/vodafone-ile-yemeksepeti-siparislerinde-100-tl-i-ndirim', destination: '/', permanent: true },
      { source: '/kampanya/vodafone-redlilere-zuppin-transferlerinde-200-tl-i-ndirim', destination: '/', permanent: true },
      { source: '/kampanya/akbank-mobil-ile-tiktak-kiralamalarinda-500-tl-i-ndirim', destination: '/', permanent: true },
      { source: '/kampanya/altinyildiz-classics-te-12-000-tl-alisverise-800-tl-bonus', destination: '/', permanent: true },
      { source: '/kampanya/enplus-ta-500-tl-maxipuan', destination: '/', permanent: true },
      { source: '/kampanya/flo-dan-money-lilere-ozel-500-tl-i-ndirim', destination: '/', permanent: true },
      { source: '/kampanya/turk-telekomlulara-yemeksepeti-mahalle-de-100-tl-i-ndirim', destination: '/', permanent: true },
      { source: '/kampanya/ovolt-ta-350-tl-ve-uzeri-harcamaya-75-tl-bonus', destination: '/', permanent: true },
      { source: '/kampanya/tatilsepeti-nde-7-500-tl-ye-varan-chip-para', destination: '/', permanent: true },
      { source: '/kampanya/turk-telekom-prime-dan-500-tl-hediye-ceki', destination: '/', permanent: true },
      { source: '/kampanya/vodafone-ile-hd-i-skender-menulerinde-i-ndirim-firsati', destination: '/', permanent: true },
      { source: '/kampanya/bosch-ev-aletlerinde-1-000-tl-bonus-firsati', destination: '/', permanent: true },
      { source: '/kampanya/vodafone-freezone-lulara-defacto-da-250-tl-i-ndirim', destination: '/', permanent: true },
      { source: '/kampanya/samsonite-alisverisinize-2-000-tl-maxipuan-firsati', destination: '/', permanent: true },
      { source: '/kampanya/superstep-alisverislerinize-500-tl-bonus-firsati', destination: '/', permanent: true },
      { source: '/kampanya/defacto-da-4-000-tl-ve-uzeri-alisverise-400-tl-bonus', destination: '/', permanent: true },
      { source: '/kampanya/house-of-superstep-te-vade-farksiz-4-taksit-firsati', destination: '/', permanent: true },
      { source: '/kampanya/ets-deki-secili-otellerde-aninda-5-ek-i-ndirim-firsati', destination: '/', permanent: true },
      { source: '/kampanya/house-of-superstep-alisverislerine-600-tl-bonus', destination: '/', permanent: true },
      { source: '/kampanya/wings-ile-yatsan-da-200-000-mil-puan-ayricaligi', destination: '/', permanent: true },
      { source: '/kampanya/vialand-tema-park-ta-gise-bilet-alimlarinda-25-indirim', destination: '/', permanent: true },
      { source: '/kampanya/i-s-kultur-yayinlari-nda-6-aya-varan-taksit-firsati', destination: '/', permanent: true },
      { source: '/kampanya/sephora-da-500-tl-maxipuan', destination: '/', permanent: true },
      { source: '/kampanya/turk-telekom-bireysel-mobil-internet-ev-telefonu-ve-tivibu-musterilerine-flyzone-trambolin-parklari-nda-35-indirim-saglanacaktir', destination: '/', permanent: true },
      { source: '/kampanya/gap-de-800-tl-ye-varan-maxipuan', destination: '/', permanent: true },
      { source: '/kampanya/de-rigo-ve-opmar-da-world-e-ozel-5-taksit-firsati', destination: '/', permanent: true },
      { source: '/kampanya/garanti-bbva-ile-defacto-alisverislerine-400-tl-bonus', destination: '/', permanent: true },
      { source: '/kampanya/kiko-milano-da-maximum-kart-a-ozel-250-tl-maxipuan', destination: '/', permanent: true },
      { source: '/kampanya/market-alisverislerinize-2-750-tl-ye-varan-maxipuan', destination: '/', permanent: true },
      { source: '/kampanya/bu-kis-hertz-ile-yapacaginiz-arac-rezervasyonlarinda-15-e-varan-tasarruf-saglayabilir-ve-normalden-3-kat-daha-fazla-mil-kazanabilirsiniz', destination: '/', permanent: true },
      { source: '/kampanya/yolcu360-tan-arac-kiralamada-i-ndirim-firsati', destination: '/', permanent: true },
      { source: '/kampanya/vaillant-ta-30-000-tl-ye-varan-indirim', destination: '/', permanent: true },
      { source: '/kampanya/maximum-dan-marks-spencer-da-maxipuan-kampanyasi', destination: '/', permanent: true },
      { source: '/kampanya/porland-alisverislerinize-300-tl-maxipuan-firsati', destination: '/', permanent: true },
      { source: '/kampanya/tikla-kazan-butonuyla-suvari-com-tr-den-yapacagin-alisverislerde-1-5-paracik-kazanabilirsin', destination: '/', permanent: true },
      { source: '/kampanya/flying-tiger-da-tum-indirimlere-ek-10-indirim', destination: '/', permanent: true },
      { source: '/kampanya/lululemon-da-1-000-tl-maxipuan', destination: '/', permanent: true },
      { source: '/kampanya/wings-ile-sok-market-harcamalarina-pesin-fiyatina-12-taksit', destination: '/', permanent: true },
      { source: '/kampanya/samsung-com-da-secili-telefon-tablet-saat-ve-kulakliklarda-5-i-ndirim', destination: '/', permanent: true },
      { source: '/kampanya/kigili-ve-abdullah-kigili-da-world-e-ozel-6-taksit-firsati', destination: '/', permanent: true },
      { source: '/kampanya/desa-da-1-500-tl-ye-varan-maxipuan', destination: '/', permanent: true },
      { source: '/kampanya/garanti-bbva-ile-puma-alisverislerine-350-tl-bonus-hediye', destination: '/', permanent: true },
      { source: '/kampanya/vodafone-yanimda-ile-kucuk-prens-sergisinde-20-i-ndirim', destination: '/', permanent: true },
      { source: '/kampanya/bosch-siemens-ve-profilo-da-world-e-ozel-6-taksit-firsati', destination: '/', permanent: true },
      { source: '/kampanya/demirdokum-harcamalarina-7-500-tl-ye-varan-i-ndirim', destination: '/', permanent: true },
      { source: '/kampanya/wings-ile-damat-tween-de-6-aya-varan-taksit', destination: '/', permanent: true },
      { source: '/kampanya/pazarama-tatil-de-otel-rezervasyonunuza-10-000-tl-ye-varan-pazaramapuan', destination: '/', permanent: true },
      { source: '/kampanya/i-stikbal-bellona-ve-mondihome-da-world-e-ozel-7-taksit-firsati', destination: '/', permanent: true },
      { source: '/kampanya/vestel-com-tr-den-yapacaginiz-vestel-kucuk-ev-aletleri-elektrikli-supurge-hoparlor-kulaklik-tablet-akilli-urunler-ve-elektrikli-sarj-istasyonu-alisverislerinde-25-indirim', destination: '/', permanent: true },
      { source: '/kampanya/tumi-de-2-500-tl-ye-varan-maxipuan', destination: '/', permanent: true },
      { source: '/kampanya/garanti-bbva-ile-defacto-da-garantipay-e-ozel-450-tl-bonus', destination: '/', permanent: true },
      { source: '/kampanya/n11-de-pesin-fiyatina-3-taksit-firsati', destination: '/', permanent: true },
      { source: '/kampanya/reebok-ta-250-tl-maxipuan-kampanyasi', destination: '/', permanent: true },
      { source: '/kampanya/garanti-bbva-ile-nike-magazalarinda-600-tl-bonus-firsati', destination: '/', permanent: true },
      { source: '/kampanya/mavi-pull-bear-bershka-oysho-ve-stradivarius-da-world-e-ozel-3-taksit-firsati', destination: '/', permanent: true },
      { source: '/kampanya/zsa-zsa-zsu-da-pesin-fiyatina-3-taksit-firsati', destination: '/', permanent: true },
      { source: '/kampanya/akbankli-kadinlara-nocturne-yeni-sezonda-30-i-ndirim', destination: '/', permanent: true },
      { source: '/kampanya/enterprise-dan-arac-kiralamalarda-ozel-i-ndirimler', destination: '/', permanent: true },
      { source: '/kampanya/mavi-magazalarinda-500-tl-maxipuan-firsati', destination: '/', permanent: true },
      { source: '/kampanya/beymen-com-da-garantipay-ile-1-000-tl-bonus-firsati', destination: '/', permanent: true },
      { source: '/kampanya/nine-west-te-pesin-fiyatina-6-taksit-firsati', destination: '/', permanent: true },
      { source: '/kampanya/i-ncehesap-com-da-pesin-fiyatina-3-taksit-firsati', destination: '/', permanent: true },
      { source: '/kampanya/pierre-cardin-de-7-000-tl-ve-uzeri-alisverise-600-tl-bonus', destination: '/', permanent: true },
      { source: '/kampanya/maximum-dan-sportive-de-250-tl-maxipuan-kampanyasi', destination: '/', permanent: true },
      { source: '/kampanya/universiteli-akbankliya-ozel-oyun-harcamalarina-50-i-ade', destination: '/', permanent: true },
      { source: '/kampanya/lastikcim-pirelli-lastikpark-lassa-ve-brisa-da-taksit-firsatlari', destination: '/', permanent: true },
      { source: '/kampanya/victoria-s-secret-harcamalarina-500-tl-maxipuan', destination: '/', permanent: true },
      { source: '/kampanya/maximum-dan-zara-massimo-dutti-oysho-bershka-pull-bear-zara-home-lefties-ve-stradivarius-magazalarindan-yapacaginiz-alisverislerde-1-000-tl-maxipuan', destination: '/', permanent: true },
      { source: '/kampanya/arcelik-altus-ve-beko-da-world-e-ozel-9-taksit-firsati', destination: '/', permanent: true },
      { source: '/kampanya/maximum-kart-ile-ets-de-15-000-tl-ye-varan-maxipuan', destination: '/', permanent: true },
      { source: '/kampanya/profilo-ev-aletlerinde-1-000-tl-bonus-firsati', destination: '/', permanent: true },
      { source: '/kampanya/elle-den-yapacaginiz-alisverislerde-tum-i-ndirimlere-ek-10-i-ndirim', destination: '/', permanent: true },
      { source: '/kampanya/flo-dan-magazalarda-gecerli-15-indirim', destination: '/', permanent: true },
      { source: '/kampanya/siemens-ev-aletlerinde-1-000-tl-bonus-firsati', destination: '/', permanent: true },
      { source: '/kampanya/carrefoursa-dan-yapacaginiz-1-000-tl-ve-uzeri-alisverislerde-100-carrefoursa-puan-hediye', destination: '/', permanent: true },
      { source: '/kampanya/d-r-cafe-kahve-kampanyasi', destination: '/', permanent: true },
      { source: '/kampanya/turkcell-lilere-ozel-instreet-alisverislerinde-gecerli-3000-tl-ve-uzeri-alisveriste-gecerli-700-tl-indirim', destination: '/', permanent: true },
    ];
  },
};

export default nextConfig;